### ISSUE TITLE
Create Function to search for growers (Users) on the landing page

### ISSUE THREAD

**Issue by uzorjchibuzor** [r-rails/plants#145]
<img width="1097" alt="Screen Shot 2022-08-29 at 2 26 21 PM" src="https://user-images.githubusercontent.com/32690770/187211940-e5f5e214-ea9f-4f11-8ee2-4670d414b2d3.png">

**Comment by czepesch** [comment]
probably it can be just "view other users"-like link to People page, not search itself

**Comment by pipen95** [comment]
Yeah sorry, I just intended to make a link to /people and /plants  pages. Not a search.
