### ISSUE TITLE
Create variable without author of the comment

### ISSUE THREAD

**Issue by czepesch** [r-rails/plants#163]
After comment is created notifications sent to every user who have this plant, including author of the comment.

app/models/comment.rb
```
  def notify_user
    notify_group = User.joins(:garden_plants).where(garden_plants: {plant_id: self.commentable_id}).all
    CommentNotification.with(comment: self).deliver_later(notify_group)
  end
```
How to exclude owner of the newly created comment from **notify_group** variable?

I tried to `notify_group = User.joins(:garden_plants).where(garden_plants: {plant_id: self.commentable_id}).all.excluding(comment.user)`
but it doesn't work.

Maybe I should try `unless` something. Any ideas?

**Comment by uzorjchibuzor** [comment]
How far along are you with this task?

**Comment by uzorjchibuzor** [comment]
This is the query I tried and it seemed to work `def notify_user
    notify_group = User.joins(:plants).where(garden_plants: {plant_id: self.commentable_id}).all.excluding(self.user)
    CommentNotification.with(comment: self).deliver_later(notify_group)
  end` @czepesch

**Comment by czepesch** [comment]
@uzorjchibuzor great, thanks! I tried different things but didn't try most obvious
