### ISSUE TITLE
Configure ActiveStorage to transform plant images

### ISSUE THREAD

**Issue by czepesch** [r-rails/plants#38]
every image that uploaded must be one size,
investigate where and how to configure it?

This [link](https://dev.to/mikerogers0/resize-images-with-active-storage-in-rails-481n) might be useful

**Comment by czepesch** [comment]
Actually I don't know how correct topic of this issue. 
We can aim in this issue to find out how to handle images, what formats to use in order to get better quality and smaller size, etc.
I heard that are newer image formats for web, do we need them?

**Comment by uzorjchibuzor** [comment]
It is still activeStorage that would be used, it might take a lot of research to get done though, I am not sure. I was thinking of taking it on but I see @pipen95 wants this. Looking forward to the implemetation.

**Comment by pipen95** [comment]
I'm going to tackle this issue this week. If I need assistance, I'll let you guys know. Thanks 😉
