### ISSUE TITLE
switch from haml to hamlit

### ISSUE THREAD

**Issue by czepesch** [r-rails/plants#49]
Hamlit is a faster implementation of Haml, so why not.
I think changing one to another should not be difficult, could you please check if your changes where .haml format works in helpers doesn't breaks with Hamlit.
https://github.com/k0kubun/hamlit
Not urgent.

**Comment by uzorjchibuzor** [comment]
We still have hamlit in our Gemfile, which is what we use in the view rendering, the haml gem is so we can write haml in helpers and presenters that will be the result of a method call. like what I did in the case of one of the partials

**Comment by uzorjchibuzor** [comment]
We still have hamlit in our Gemfile, which is what we use in the view rendering, the haml gem is so we can write haml in helpers and presenters that will be the result of a method call. like what I did in the case of one of the partials

**Comment by czepesch** [comment]
okay, I thought maybe hamlit gem can do same thing in helpers so we don't have to keep two gems, if not, you can close the issue.
