### ISSUE TITLE
keep\redirect user on the page where he started sign in process

### ISSUE THREAD

**Issue by czepesch** [r-rails/plants#55]
maybe this thread will be helpful:
https://stackoverflow.com/questions/13129254/how-to-direct-user-to-a-specific-page-after-logging-in-with-devise-and-rails

**Comment by uzorjchibuzor** [comment]
According to the blog post, we are going to need some before callbacks placed in our application controller that will keep track of the link a user wanted to get before the signin process. I am going to work on this later as I am about to run out power on my computer and there is no gas.
